apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-deployment
  labels:
    app: super-mario
spec:
  replicas: 1 # Mínimo de réplicas para un nodo f1-micro
  selector:
    matchLabels:
      app: super-mario
  template:
    metadata:
      labels:
        app: super-mario
    spec:
      containers:
      - name: mario-web
        image: mario20/super-mario-bros:latest # <-- ¡Imagen de Super Mario!
        ports:
        - containerPort: 80 # Asumo que esta imagen sirve en el puerto 80
        resources:
          requests: # Solicitud mínima de recursos
            cpu: "75m"  # Un poco más de CPU por si acaso
            memory: "96Mi" # Un poco más de RAM por si acaso
          limits:
            cpu: "150m"
            memory: "192Mi"
