apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game-deployment
  # namespace: mi-app-ns # Descomenta si usas un namespace específico
  labels:
    app: snake-game
spec:
  replicas: 1 # Mínimo de réplicas para un nodo f1-micro
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      containers:
      - name: snake-game
        image: mcr.microsoft.com/oss/kubernetes/snake:v1 # <-- ¡Imagen de juego de Snake!
        ports:
        - containerPort: 80 # El juego de Snake suele servir en el puerto 80
        resources:
          requests: # Solicitud mínima de recursos para un f1-micro
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
