apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-game-deployment
  # namespace: mi-app-ns # Descomenta si usas un namespace específico
  labels:
    app: pacman-game
spec:
  replicas: 1 # Mínimo de réplicas para un nodo f1-micro
  selector:
    matchLabels:
      app: pacman-game
  template:
    metadata:
      labels:
        app: pacman-game
    spec:
      containers:
      - name: pacman
        image: denysvitali/pacman:latest # <-- ¡Imagen de Pac-Man verificada!
        ports:
        - containerPort: 80 # Se asume que el juego Pac-Man sirve en el puerto 80
        resources:
          requests: # Solicitud mínima de recursos para un f1-micro
            cpu: "75m"  # Un poco más que Nginx por ser un juego
            memory: "96Mi" # Un poco más que Nginx por ser un juego
          limits:
            cpu: "150m"
            memory: "192Mi"
