apiVersion: apps/v1
kind: Deployment
metadata:
  name: supertuxkart-game-deployment
  labels:
    app: supertuxkart-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supertuxkart-game
  template:
    metadata:
      labels:
        app: supertuxkart-game
    spec:
      containers:
      - name: supertuxkart
        image: linuxserver/supertuxkart
        ports:
        - containerPort: 8080 # Supertuxkart no sirve en puerto, placeholder si deseas exponer interfaz
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
