apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game-deployment
  labels:
    app: snake-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      containers:
      - name: snake
        image: jess/snake
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "75m"
            memory: "96Mi"
          limits:
            cpu: "150m"
            memory: "192Mi"

