apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048-deployment
  # namespace: mi-app-ns # Descomenta si usas un namespace específico
  labels:
    app: game-2048
spec:
  replicas: 1 # Mínimo de réplicas para un nodo f1-micro
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
      - name: game-2048
        image: alexwhen/docker-2048:latest # <-- ¡Imagen pública del juego 2048!
        ports:
        - containerPort: 80 # El juego 2048 suele servir en el puerto 80
        resources:
          requests: # Solicitud mínima de recursos para un f1-micro
            cpu: "50m" # 50 milicores de CPU (0.05 CPU)
            memory: "64Mi" # 64 megabytes de memoria.
          limits:
            cpu: "100m" # 100 milicores de CPU (0.1 CPU)
            memory: "128Mi" # 128 megabytes de memoria.

