apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-game-deployment
  labels:
    app: tetris-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris-game
  template:
    metadata:
      labels:
        app: tetris-game
    spec:
      containers:
      - name: tetris
        image: nacyot/docker-tetris
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "75m"
            memory: "96Mi"
          limits:
            cpu: "150m"
            memory: "192Mi"
